# Generated by Django 3.1.1 on 2020-09-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=40)),
                ('long_url', models.URLField(unique=True, verbose_name='URL')),
            ],
        ),
    ]
